//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatCompanyCherc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accessory()
        {
            this.BoatAccessory = new HashSet<BoatAccessory>();
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int id { get; set; }
        public string accName { get; set; }
        public string decriptionOfAccessory { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<int> inventory { get; set; }
        public Nullable<int> orderLevel { get; set; }
        public Nullable<int> orderBatch { get; set; }
        public Nullable<int> partner_id { get; set; }
    
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoatAccessory> BoatAccessory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
