//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatCompanyCherc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> depositPayed { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<decimal> contractTotalPrice { get; set; }
        public Nullable<decimal> ContracTotalPrice_inclVAT { get; set; }
        public Nullable<int> production_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ProdictionProcess ProdictionProcess { get; set; }
    }
}
